controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

    gains:
      joint_1_s: { p: 50.0, d: 5.0, i: 0.1, i_clamp: 1.0 }
      joint_2_l: { p: 50.0, d: 5.0, i: 0.1, i_clamp: 1.0 }
      joint_3_u: { p: 50.0, d: 5.0, i: 0.1, i_clamp: 1.0 }
      joint_4_r: { p: 50.0, d: 5.0, i: 0.1, i_clamp: 1.0 }
      joint_5_b: { p: 50.0, d: 5.0, i: 0.1, i_clamp: 1.0 }
      joint_6_t: { p: 50.0, d: 5.0, i: 0.1, i_clamp: 1.0 }
