#!/usr/bin/env python3
"""
Simple bridge to republish /isaac_joint_states to /joint_states for MoveIt.

Generated by Claude Opus 4.5
"""
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState
from moveit_msgs.msg import RobotState

class JointStateBridge(Node):
    def __init__(self):
        super().__init__('joint_state_bridge')
        
        # Subscribe to Isaac Sim joint states
        self.subscription = self.create_subscription(
            JointState,
            '/isaac_joint_states',
            self.joint_state_callback,
            10
        )
        
        # Publish to MoveIt's expected topic
        self.publisher = self.create_publisher(
            JointState,
            '/joint_states',
            10
        )

        self.robot_state_publisher = self.create_publisher(
            RobotState,
            '/robot_state',
            10
        )
        
        self.get_logger().info('Joint state bridge ready')
        self.get_logger().info('Subscribing to: /isaac_joint_states')
        self.get_logger().info('Publishing to: /joint_states')
    
    def joint_state_callback(self, msg):
        """Republish joint states from Isaac Sim to MoveIt"""
        self.publisher.publish(msg)
        self.robot_state_publisher.publish(RobotState(joint_state=msg))
        
def main(args=None):
    rclpy.init(args=args)
    node = JointStateBridge()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        try:
            rclpy.shutdown()
        except Exception:
            pass

if __name__ == '__main__':
    main()

